export const ring: {
    "blue-gray": string;
    gray: string;
    brown: string;
    "deep-orange": string;
    orange: string;
    amber: string;
    yellow: string;
    lime: string;
    "light-green": string;
    green: string;
    teal: string;
    cyan: string;
    "light-blue": string;
    blue: string;
    indigo: string;
    "deep-purple": string;
    purple: string;
    pink: string;
    red: string;
};
